export const ADD_TOKEN = 'ADD_TOKEN';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_URLS = 'SET_URLS';
export const SET_SELECTED_RESTAURANTS = 'SET_SELECTED_RESTAURANTS'
export const SET_EVENT_DATE = 'SET_EVENT_DATE'
export const SET_EVENT_DEADLINE_DATE = 'SET_EVENT_DEADLINE_DATE'